## Numpy

In [1]:
import numpy as np

## Datatypes and Attributes

In [2]:
# Numpy's main datatype is ndarrray (for n-dimensional array)
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
# We can also create matrices!
matrix = np.array([[1.0, 2.0, 3.0], [4, 5, 6]])
matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
# But it has the same type as a 1-dimensional array, that is, ndarray
type(matrix)

numpy.ndarray

In [6]:
# We can inspect teh shape of a ndarray
matrix.shape

(2, 3)

In [8]:
# And the number of dimensions
matrix.ndim

2

In [9]:
# ndarrays also have dtype
matrix.dtype

dtype('float64')

In [10]:
# If we wnat to know the number of values stored in a ndarray
matrix.size

6

In [13]:
# We can also create a dataframe from numpy arrays
import pandas as pd
dataframe = pd.DataFrame(matrix)
dataframe

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.0

## Creating NumPy Arrays

In [14]:
# As we saw, we can create arrays the simple way
simple = np.array([1,2,3])
simple

array([1, 2, 3])

In [21]:
# We can create an array of any shape filled with ones
ones = np.ones(shape=(2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# Or an array filled with zeros
zeros = np.zeros(shape=(2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# Or even a array spannign a range of numbers
arange = np.arange(0, 5, 1)
arange

array([0, 1, 2, 3, 4])

In [28]:
# An array with random integers
randint = np.random.randint(0, 10, size=(3,5))
randint

array([[3, 1, 6, 6, 2],
       [6, 5, 3, 3, 7],
       [4, 8, 8, 6, 2]])

In [31]:
# Random floats in [0,1) (uniform distribution)
random = np.random.random(size=(3,5))
random

array([[0.51071897, 0.8069879 , 0.58327188, 0.69069546, 0.07057833],
       [0.30951962, 0.63037142, 0.43009029, 0.29009977, 0.63893528],
       [0.06639732, 0.58257714, 0.8595088 , 0.03442301, 0.18650972]])

In [33]:
rand = np.random.rand(3,5)
rand

array([[0.5974418 , 0.04819377, 0.3353651 , 0.61891132, 0.85292274],
       [0.00871458, 0.67447811, 0.2235099 , 0.01913127, 0.14249261],
       [0.70205447, 0.18746079, 0.99444673, 0.02716952, 0.31407594]])

In [41]:
# Array with values from a normal distribution
norm = np.random.normal(size=(10))
norm

array([-0.93095467,  0.14885435, -1.56765988,  1.54640052, -2.36557373,
       -1.49823443, -1.47634938, -0.85335366,  0.29087283, -2.11273868])

In [58]:
# Random numbers are generated from a random seed, if we set a fixed seed we always get the same number
# Run this cell multiple times an you will see the value doesn't change
np.random.seed(0)
np.random.normal()

1.764052345967664